### ISSUE TITLE
support macOS 10.15.7

### ISSUE THREAD

**Issue by Cregin** [EamonTracey/iPatch#2]
macOS 10.15.7 don't work

**Comment by sourcelocation** [comment]
The app is written in SwiftUI and it only supports MacOS 11.0. It can be possible to rewrite it in UIKit, but that will take some time. And it seems, that the developer says nothing about it, so _I could do it_ if I will have enough free time.

**Comment by Cregin** [comment]
thanks.

**Comment by sourcelocation** [comment]
Made a fork with MacOS >= 10.10 support!
https://github.com/ExeRhythm/iPatch
